services:
#  user-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/senior_project
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      SPRING_MAIL_HOST: smtp.gmail.com
#      SPRING_MAIL_USERNAME: your-email@gmail.com
#      SPRING_MAIL_PASSWORD: your-email-password
#    depends_on:
#      - database
  postgres-db:
    image: postgres:17.0
#    container-name: postgres-db
#    restart: always
    ports:
      - "5434:5434"
    environment:
      POSTGRES_DB: university-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qazplm
    volumes:
      - ./data:/var/lib/postgresql/data
