services:
  backend:
    build: .
    container_name: uni-trello-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - university_net
  db:
    image: postgres:17
    container_name: university_postgres
    environment:
      POSTGRES_DB: university_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qazplm
    ports:
      - "5434:5434"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - university_net

volumes:
  db_data:

networks:
  university_net:
